package com.toutiaopoker.web.model;

import java.util.Date;

public class HeadlineNews {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column headline_news.NEWS_ID
     *
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    private String newsId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column headline_news.NEWS_TITLE
     *
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    private String newsTitle;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column headline_news.NEWS_COVER_IMG
     *
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    private String newsCoverImg;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column headline_news.NEWS_CREATE_TIME
     *
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    private Date newsCreateTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column headline_news.NEWS_UPDATE_TIME
     *
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    private Date newsUpdateTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column headline_news.NEWS_START_TIME
     *
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    private Date newsStartTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column headline_news.NEWS_END_TIME
     *
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    private Date newsEndTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column headline_news.NEWS_SORT
     *
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    private Integer newsSort;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column headline_news.NEWS_TYPE
     *
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    private String newsType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column headline_news.NEWS_STATUS
     *
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    private Integer newsStatus;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column headline_news.NEWS_DETAIL
     *
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    private String newsDetail;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column headline_news.NEWS_ID
     *
     * @return the value of headline_news.NEWS_ID
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    public String getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column headline_news.NEWS_ID
     *
     * @param newsId the value for headline_news.NEWS_ID
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    public void setNewsId(String newsId) {
        this.newsId = newsId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column headline_news.NEWS_TITLE
     *
     * @return the value of headline_news.NEWS_TITLE
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    public String getNewsTitle() {
        return newsTitle;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column headline_news.NEWS_TITLE
     *
     * @param newsTitle the value for headline_news.NEWS_TITLE
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    public void setNewsTitle(String newsTitle) {
        this.newsTitle = newsTitle;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column headline_news.NEWS_COVER_IMG
     *
     * @return the value of headline_news.NEWS_COVER_IMG
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    public String getNewsCoverImg() {
        return newsCoverImg;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column headline_news.NEWS_COVER_IMG
     *
     * @param newsCoverImg the value for headline_news.NEWS_COVER_IMG
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    public void setNewsCoverImg(String newsCoverImg) {
        this.newsCoverImg = newsCoverImg;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column headline_news.NEWS_CREATE_TIME
     *
     * @return the value of headline_news.NEWS_CREATE_TIME
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    public Date getNewsCreateTime() {
        return newsCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column headline_news.NEWS_CREATE_TIME
     *
     * @param newsCreateTime the value for headline_news.NEWS_CREATE_TIME
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    public void setNewsCreateTime(Date newsCreateTime) {
        this.newsCreateTime = newsCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column headline_news.NEWS_UPDATE_TIME
     *
     * @return the value of headline_news.NEWS_UPDATE_TIME
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    public Date getNewsUpdateTime() {
        return newsUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column headline_news.NEWS_UPDATE_TIME
     *
     * @param newsUpdateTime the value for headline_news.NEWS_UPDATE_TIME
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    public void setNewsUpdateTime(Date newsUpdateTime) {
        this.newsUpdateTime = newsUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column headline_news.NEWS_START_TIME
     *
     * @return the value of headline_news.NEWS_START_TIME
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    public Date getNewsStartTime() {
        return newsStartTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column headline_news.NEWS_START_TIME
     *
     * @param newsStartTime the value for headline_news.NEWS_START_TIME
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    public void setNewsStartTime(Date newsStartTime) {
        this.newsStartTime = newsStartTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column headline_news.NEWS_END_TIME
     *
     * @return the value of headline_news.NEWS_END_TIME
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    public Date getNewsEndTime() {
        return newsEndTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column headline_news.NEWS_END_TIME
     *
     * @param newsEndTime the value for headline_news.NEWS_END_TIME
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    public void setNewsEndTime(Date newsEndTime) {
        this.newsEndTime = newsEndTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column headline_news.NEWS_SORT
     *
     * @return the value of headline_news.NEWS_SORT
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    public Integer getNewsSort() {
        return newsSort;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column headline_news.NEWS_SORT
     *
     * @param newsSort the value for headline_news.NEWS_SORT
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    public void setNewsSort(Integer newsSort) {
        this.newsSort = newsSort;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column headline_news.NEWS_TYPE
     *
     * @return the value of headline_news.NEWS_TYPE
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    public String getNewsType() {
        return newsType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column headline_news.NEWS_TYPE
     *
     * @param newsType the value for headline_news.NEWS_TYPE
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    public void setNewsType(String newsType) {
        this.newsType = newsType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column headline_news.NEWS_STATUS
     *
     * @return the value of headline_news.NEWS_STATUS
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    public Integer getNewsStatus() {
        return newsStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column headline_news.NEWS_STATUS
     *
     * @param newsStatus the value for headline_news.NEWS_STATUS
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    public void setNewsStatus(Integer newsStatus) {
        this.newsStatus = newsStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column headline_news.NEWS_DETAIL
     *
     * @return the value of headline_news.NEWS_DETAIL
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    public String getNewsDetail() {
        return newsDetail;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column headline_news.NEWS_DETAIL
     *
     * @param newsDetail the value for headline_news.NEWS_DETAIL
     * @mbggenerated Tue Aug 14 12:59:46 CST 2018
     */
    public void setNewsDetail(String newsDetail) {
        this.newsDetail = newsDetail;
    }

}